apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sunnyvale-it-folding-at-k8s.fullname" . }}-ds
  labels:
    {{- include "sunnyvale-it-folding-at-k8s.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sunnyvale-it-folding-at-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sunnyvale-it-folding-at-k8s.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "sunnyvale-it-folding-at-k8s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "sunnyvale/folding-at-k8s:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7396
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/etc/fahclient"
            - name: logs
              mountPath: "/var/lib/fahclient"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "sunnyvale-it-folding-at-k8s.fullname" . }}-cm
          items:
            - key: config.xml
              path: config.xml
      - name: logs
        emptyDir: {}
