apiVersion: v1
kind: Service
metadata:
  name: {{ include "sunnyvale-it-folding-at-k8s.fullname" . }}-svc
  labels:
    {{- include "sunnyvale-it-folding-at-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sunnyvale-it-folding-at-k8s.selectorLabels" . | nindent 4 }}
